/*
 * This file is generated by jOOQ.
 */
package dev.gregopet.blabla


import dev.gregopet.blabla.tables.Hamburger

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC = Public()
    }

    /**
     * The table <code>public.hamburger</code>.
     */
    val HAMBURGER get() = Hamburger.HAMBURGER

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Hamburger.HAMBURGER
    )
}
