/*
 * This file is generated by jOOQ.
 */
package dev.gregopet.blabla.tables.references


import dev.gregopet.blabla.tables.Hamburger



/**
 * The table <code>public.hamburger</code>.
 */
val HAMBURGER = Hamburger.HAMBURGER
